[workspace]
resolver = "2"
members = [
  "mdbook/src/03-setup",
  "mdbook/src/05-led-roulette",
  "mdbook/src/07-uart",
  "mdbook/src/08-i2c",
  "mdbook/src/09-led-compass",
  "mdbook/src/10-punch-o-meter",
  "mdbook/src/11-snake-game", "mdbook/src/serial-setup",
]

[profile.release]
codegen-units = 1
debug = true
lto = true
